# Generated by Django 2.2.28 on 2022-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hello',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
