# Generated by Django 2.2.28 on 2022-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221209_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
